# PATIENT SURVIVAL PREDICTION

Import Libraries

In [1]:
import pandas as pd
import numpy as np

Import Dataset

In [2]:
df=pd.read_csv('train2.csv')

In [3]:
df.shape

(18477, 18)

In [4]:
df

,ID_Patient_Care_Situation,Diagnosed_Condition,Patient_ID,Treated_with_drugs,Patient_Age,Patient_Body_Mass_Index,Patient_Smoker,Patient_Rural_Urban,Patient_mental_condition,A,B,C,D,E,F,Z,Number_of_prev_cond,Survived_1_year
0,21388,6,10452,DX1 DX4,23,19.199662,YES,RURAL,Stable,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1
1,1990,10,5807,DX1 DX5,65,18.354031,YES,URBAN,Stable,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2.0,0
2,16710,43,11802,DX6,2,24.732770,NO,RURAL,Stable,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
3,29293,32,6863,DX2 DX3,57,22.204759,NO,URBAN,Stable,1.0,1.0,0.0,1.0,0.0,0.0,0.0,3.0,1
4,24007,14,1495,DX6,66,23.883381,YES,RURAL,Stable,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18472,22176,45,4759,DX2 DX3,65,24.155042,NO,RURAL,Stable,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
18473,9834,36,8294,DX6,41,29.557805,YES,RURAL,Stable,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,1
18474,23932,44,2107,DX4,48,25.242448,YES,RURAL,Stable,1.0,0.0,1.0,0.0,1.0,0.0,0.0,3.0,1
18475,24076,45,6016,DX3,47,29.921929,YES,RURAL,Stable,1.0,0.0,0.0,1.0,1.0,0.0,0.0,3.0,0
18476,24554,13,9914,DX3,47,19.603383,NO,RURAL,Stable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

Data Preprocessing

In [5]:
df.isnull().sum()

ID_Patient_Care_Situation       0
Diagnosed_Condition             0
Patient_ID                      0
Treated_with_drugs              8
Patient_Age                     0
Patient_Body_Mass_Index         0
Patient_Smoker                  0
Patient_Rural_Urban             0
Patient_mental_condition        0
A                            1005
B                            1005
C                            1005
D                            1005
E                            1005
F                            1005
Z                            1005
Number_of_prev_cond          1005
Survived_1_year                 0
dtype: int64

In [8]:
cols_nan=['A','B','C','D','E','F','Z']
for cols in cols_nan:
    df[cols].fillna(0,inplace=True)

In [9]:
df.isnull().sum()

ID_Patient_Care_Situation       0
Diagnosed_Condition             0
Patient_ID                      0
Treated_with_drugs              8
Patient_Age                     0
Patient_Body_Mass_Index         0
Patient_Smoker                  0
Patient_Rural_Urban             0
Patient_mental_condition        0
A                               0
B                               0
C                               0
D                               0
E                               0
F                               0
Z                               0
Number_of_prev_cond          1005
Survived_1_year                 0
dtype: int64

In [10]:

df['Number_of_prev_cond'].fillna(df['A']+df['B']+df['C']+df['D']+df['E']+df['F']+df['Z'],inplace=True)

In [11]:
df.isnull().sum()

ID_Patient_Care_Situation    0
Diagnosed_Condition          0
Patient_ID                   0
Treated_with_drugs           8
Patient_Age                  0
Patient_Body_Mass_Index      0
Patient_Smoker               0
Patient_Rural_Urban          0
Patient_mental_condition     0
A                            0
B                            0
C                            0
D                            0
E                            0
F                            0
Z                            0
Number_of_prev_cond          0
Survived_1_year              0
dtype: int64

Null Values Removed

In [12]:
df['Treated_with_drugs'].unique()

array(['DX1 DX4 ', 'DX1 DX5 ', 'DX6', 'DX2 DX3 ', 'DX2 ', 'DX4 DX5 ',
       'DX1 ', 'DX5 ', 'DX1 DX2 DX4 ', 'DX1 DX2 ', 'DX4 ', 'DX2 DX4 ',
       'DX3 ', 'DX3 DX5 ', 'DX1 DX3 DX5 ', 'DX3 DX4 ', 'DX1 DX3 DX4 ',
       'DX2 DX4 DX5 ', 'DX1 DX2 DX5 ', 'DX1 DX4 DX5 ', 'DX2 DX5 ',
       'DX1 DX3 ', 'DX2 DX3 DX4 ', 'DX1 DX2 DX3 ', 'DX1 DX2 DX3 DX5 ',
       'DX2 DX3 DX5 ', 'DX3 DX4 DX5 ', 'DX1 DX2 DX4 DX5 ',
       'DX2 DX3 DX4 DX5 ', nan, 'DX1 DX3 DX4 DX5 ', 'DX1 DX2 DX3 DX4 ',
       'DX1 DX2 DX3 DX4 DX5 '], dtype=object)

In [13]:
count1=count2=count3=count4=count5=count6=count7=0
for row in df['Treated_with_drugs']:
    val=str(row).split(" ")
    for value in val:
        if value == 'DX1':
            count1+=1
        elif value == 'DX2':
            count2+=1
        elif value == 'DX3':
            count3+=1
        elif value == 'DX4':
            count4+=1
        elif value == 'DX5':
            count5+=1
        elif value == 'DX6':
            count6+=1
        else:
            count7+=1
print(count1,count2,count3,count4,count5,count6,count7)

3331 3390 3320 3275 3368 6862 11615

In [14]:
df['Treated_with_drugs'].fillna("DX6",inplace=True)

In [15]:
df.isnull().sum()

ID_Patient_Care_Situation    0
Diagnosed_Condition          0
Patient_ID                   0
Treated_with_drugs           0
Patient_Age                  0
Patient_Body_Mass_Index      0
Patient_Smoker               0
Patient_Rural_Urban          0
Patient_mental_condition     0
A                            0
B                            0
C                            0
D                            0
E                            0
F                            0
Z                            0
Number_of_prev_cond          0
Survived_1_year              0
dtype: int64

In [16]:
df.dtypes

ID_Patient_Care_Situation      int64
Diagnosed_Condition            int64
Patient_ID                     int64
Treated_with_drugs            object
Patient_Age                    int64
Patient_Body_Mass_Index      float64
Patient_Smoker                object
Patient_Rural_Urban           object
Patient_mental_condition      object
A                            float64
B                            float64
C                            float64
D                            float64
E                            float64
F                            float64
Z                            float64
Number_of_prev_cond          float64
Survived_1_year                int64
dtype: object

In [17]:
df1=pd.DataFrame(np.zeros((18477,6)))
df1.columns=['DX1','DX2','DX3','DX4','DX5','DX6']
count_row=0
for row in df['Treated_with_drugs']:   
    val=str(row).split(" ")
    for value in val:
        if value == 'DX1':
            df1.loc[count_row,"DX1"]=1
        elif value == 'DX2':
            df1.loc[count_row,"DX2"]=1
        elif value == 'DX3':
            df1.loc[count_row,"DX3"]=1
        elif value == 'DX4':
            df1.loc[count_row,"DX4"]=1
        elif value == 'DX5':
            df1.loc[count_row,"DX5"]=1
        elif value == 'DX6':
            df1.loc[count_row,"DX6"]=1
    count_row+=1
df1

       DX1  DX2  DX3  DX4  DX5  DX6
0      1.0  0.0  0.0  1.0  0.0  0.0
1      1.0  0.0  0.0  0.0  1.0  0.0
2      0.0  0.0  0.0  0.0  0.0  1.0
3      0.0  1.0  1.0  0.0  0.0  0.0
4      0.0  0.0  0.0  0.0  0.0  1.0
...    ...  ...  ...  ...  ...  ...
18472  0.0  1.0  1.0  0.0  0.0  0.0
18473  0.0  0.0  0.0  0.0  0.0  1.0
18474  0.0  0.0  0.0  1.0  0.0  0.0
18475  0.0  0.0  1.0  0.0  0.0  0.0
18476  0.0  0.0  1.0  0.0  0.0  0.0

[18477 rows x 6 columns]

In [18]:
df=pd.concat([df,df1],axis=1)

In [19]:
df

,ID_Patient_Care_Situation,Diagnosed_Condition,Patient_ID,Treated_with_drugs,Patient_Age,Patient_Body_Mass_Index,Patient_Smoker,Patient_Rural_Urban,Patient_mental_condition,A,...,F,Z,Number_of_prev_cond,Survived_1_year,DX1,DX2,DX3,DX4,DX5,DX6
0,21388,6,10452,DX1 DX4,23,19.199662,YES,RURAL,Stable,0.0,...,0.0,0.0,1.0,1,1.0,0.0,0.0,1.0,0.0,0.0
1,1990,10,5807,DX1 DX5,65,18.354031,YES,URBAN,Stable,0.0,...,0.0,0.0,2.0,0,1.0,0.0,0.0,0.0,1.0,0.0
2,16710,43,11802,DX6,2,24.732770,NO,RURAL,Stable,1.0,...,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,0.0,1.0
3,29293,32,6863,DX2 DX3,57,22.204759,NO,URBAN,Stable,1.0,...,0.0,0.0,3.0,1,0.0,1.0,1.0,0.0,0.0,0.0
4,24007,14,1495,DX6,66,23.883381,YES,RURAL,Stable,1.0,...,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18472,22176,45,4759,DX2 DX3,65,24.155042,NO,RURAL,Stable,1.0,...,0.0,0.0,1.0,1,0.0,1.0,1.0,0.0,0.0,0.0
18473,9834,36,8294,DX6,41,29.557805,YES,RURAL,Stable,1.0,...,0.0,0.0,2.0,1,0.0,0.0,0.0,0.0,0.0,1.0
18474,23932,44,2107,DX4,48,25.242448,YES,RURAL,Stable,1.0,...,0.0,0.0,3.0,1,0.0,0.0,0.0,1.0,0.0,0.0
18475,24076,45,6016,DX3,47,29.921929,YES,RURAL,Stable,1.0,...,0.0,0.0,3.0,0,0.0,0.0,1.0,0.0,0.0,0.0
18476,24554,13,9914,DX3,47,19.603383,NO,RURAL,Stable,0.0,...,0.0,0.0,0.0,1,0.0,0.0,1.0,0.0,0.0,0.0

In [20]:
df.drop('Treated_with_drugs',axis=1,inplace=True)

In [21]:
df

,ID_Patient_Care_Situation,Diagnosed_Condition,Patient_ID,Patient_Age,Patient_Body_Mass_Index,Patient_Smoker,Patient_Rural_Urban,Patient_mental_condition,A,B,...,F,Z,Number_of_prev_cond,Survived_1_year,DX1,DX2,DX3,DX4,DX5,DX6
0,21388,6,10452,23,19.199662,YES,RURAL,Stable,0.0,0.0,...,0.0,0.0,1.0,1,1.0,0.0,0.0,1.0,0.0,0.0
1,1990,10,5807,65,18.354031,YES,URBAN,Stable,0.0,1.0,...,0.0,0.0,2.0,0,1.0,0.0,0.0,0.0,1.0,0.0
2,16710,43,11802,2,24.732770,NO,RURAL,Stable,1.0,0.0,...,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,0.0,1.0
3,29293,32,6863,57,22.204759,NO,URBAN,Stable,1.0,1.0,...,0.0,0.0,3.0,1,0.0,1.0,1.0,0.0,0.0,0.0
4,24007,14,1495,66,23.883381,YES,RURAL,Stable,1.0,0.0,...,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18472,22176,45,4759,65,24.155042,NO,RURAL,Stable,1.0,0.0,...,0.0,0.0,1.0,1,0.0,1.0,1.0,0.0,0.0,0.0
18473,9834,36,8294,41,29.557805,YES,RURAL,Stable,1.0,1.0,...,0.0,0.0,2.0,1,0.0,0.0,0.0,0.0,0.0,1.0
18474,23932,44,2107,48,25.242448,YES,RURAL,Stable,1.0,0.0,...,0.0,0.0,3.0,1,0.0,0.0,0.0,1.0,0.0,0.0
18475,24076,45,6016,47,29.921929,YES,RURAL,Stable,1.0,0.0,...,0.0,0.0,3.0,0,0.0,0.0,1.0,0.0,0.0,0.0
18476,24554,13,9914,47,19.603383,NO,RURAL,Stable,0.0,0.0,...,0.0,0.0,0.0,1,0.0,0.0,1.0,0.0,0.0,0.0

In [22]:
df.groupby('Number_of_prev_cond').mean()

,ID_Patient_Care_Situation,Diagnosed_Condition,Patient_ID,Patient_Age,Patient_Body_Mass_Index,A,B,C,D,E,F,Z,Survived_1_year,DX1,DX2,DX3,DX4,DX5,DX6
Number_of_prev_cond,,,,,,,,,,,,,,,,,,,
0.0,16876.314428,26.793035,6287.420896,31.384080,23.742373,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.773134,0.176119,0.197015,0.183085,0.190050,0.191045,0.368159
1.0,16396.571143,26.383518,6284.613415,33.735165,23.450294,0.838112,0.016135,0.033471,0.013869,0.088278,0.009068,0.001067,0.651954,0.178957,0.185491,0.174690,0.170289,0.183891,0.375117
2.0,16691.962264,26.591565,6256.910794,32.811598,23.515330,0.934378,0.164123,0.209906,0.083657,0.552997,0.054939,0.000000,0.625971,0.181326,0.175499,0.180216,0.180771,0.174806,0.374029
3.0,16606.143507,26.419768,6299.678246,33.563689,23.124621,0.968983,0.364351,0.504963,0.240281,0.776261,0.145161,0.000000,0.574442,0.182796,0.201820,0.191894,0.178660,0.197684,0.354839
4.0,16836.315625,26.565625,5756.090625,32.468750,23.627876,0.993750,0.568750,0.787500,0.421875,0.890625,0.337500,0.000000,0.353125,0.178125,0.125000,0.171875,0.209375,0.178125,0.387500
5.0,14316.629630,26.333333,5534.407407,26.925926,21.724894,1.000000,0.925926,0.851852,0.777778,0.851852,0.592593,0.000000,0.074074,0.222222,0.296296,0.296296,0.185185,0.074074,0.333333

In [23]:
df['Patient_Smoker'].unique()

array(['YES', 'NO', 'Cannot say'], dtype=object)

In [24]:
cols_del=['Patient_mental_condition','Patient_ID']
for cols in cols_del:
    df.drop(cols,inplace=True,axis=1)

In [25]:
col_dum=['Patient_Smoker','Patient_Rural_Urban']
for cols in col_dum:
    dummies=pd.get_dummies(df[cols])
    df=pd.concat([df,dummies],axis=1)
df.drop(col_dum,axis=1,inplace=True)

In [26]:
df

,ID_Patient_Care_Situation,Diagnosed_Condition,Patient_Age,Patient_Body_Mass_Index,A,B,C,D,E,F,...,DX2,DX3,DX4,DX5,DX6,Cannot say,NO,YES,RURAL,URBAN
0,21388,6,23,19.199662,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0,0,1,1,0
1,1990,10,65,18.354031,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0,0,1,0,1
2,16710,43,2,24.732770,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0,1,0,1,0
3,29293,32,57,22.204759,1.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0,1,0,0,1
4,24007,14,66,23.883381,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18472,22176,45,65,24.155042,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0,1,0,1,0
18473,9834,36,41,29.557805,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0,0,1,1,0
18474,23932,44,48,25.242448,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0,0,1,1,0
18475,24076,45,47,29.921929,1.0,0.0,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0,0,1,1,0
18476,24554,13,47,19.603383,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0,1,0,1,0

In [27]:
cols_to_scale=['ID_Patient_Care_Situation','Diagnosed_Condition','Patient_Body_Mass_Index','Patient_Age']
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
df[cols_to_scale]=scaler.fit_transform(df[cols_to_scale])

In [28]:
df

,ID_Patient_Care_Situation,Diagnosed_Condition,Patient_Age,Patient_Body_Mass_Index,A,B,C,D,E,F,...,DX2,DX3,DX4,DX5,DX6,Cannot say,NO,YES,RURAL,URBAN
0,0.647825,0.115385,0.154362,0.626433,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0,0,1,1,0
1,0.060221,0.192308,0.436242,0.597183,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0,0,1,0,1
2,0.506119,0.826923,0.013423,0.817822,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0,1,0,1,0
3,0.887283,0.615385,0.382550,0.730379,1.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0,1,0,0,1
4,0.727160,0.269231,0.442953,0.788442,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18472,0.671695,0.865385,0.436242,0.797839,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0,1,0,1,0
18473,0.297831,0.692308,0.275168,0.984719,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0,0,1,1,0
18474,0.724888,0.846154,0.322148,0.835452,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0,0,1,1,0
18475,0.729250,0.865385,0.315436,0.997314,1.0,0.0,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0,0,1,1,0
18476,0.743730,0.250000,0.315436,0.640398,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0,1,0,1,0

In [29]:
X=df.drop('Survived_1_year',axis=1)
y=df['Survived_1_year']

In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=10)

In [30]:
num_class=len(X_train.columns)
model=Sequential([
    keras.layers.Dense(20,input_shape=(num_class,),activation='relu'),
    keras.layers.Dense(10,activation='softmax'),
    keras.layers.Dense(1,activation='sigmoid')
])
model.compile(optimizer="adam",
             loss="binary_crossentropy",
             metrics=['accuracy'])
model.fit(X_train,y_train,epochs=100)

Epoch 1/100
462/462 [==============================] - 1s 1ms/step - loss: 0.6399 - accuracy: 0.6688
Epoch 2/100
462/462 [==============================] - 0s 1ms/step - loss: 0.5601 - accuracy: 0.7208
Epoch 3/100
462/462 [==============================] - 0s 1ms/step - loss: 0.5502 - accuracy: 0.7242
Epoch 4/100
462/462 [==============================] - 0s 1ms/step - loss: 0.5497 - accuracy: 0.7216
Epoch 5/100
462/462 [==============================] - 0s 1ms/step - loss: 0.5371 - accuracy: 0.7327
Epoch 6/100
462/462 [==============================] - 0s 1ms/step - loss: 0.5344 - accuracy: 0.7301
Epoch 7/100
462/462 [==============================] - 0s 1ms/step - loss: 0.5299 - accuracy: 0.7314
Epoch 8/100
462/462 [==============================] - 0s 1ms/step - loss: 0.5294 - accuracy: 0.7314
Epoch 9/100
462/462 [==============================] - 0s 1ms/step - loss: 0.5276 - accuracy: 0.7285
Epoch 10/100
462/462 [==============================] - 0s 1ms/step - loss: 0.5235 - accuracy: 0.7363
Epoch 11/100
462/462 [==============================] - 0s 1ms/step - loss: 0.5132 - accuracy: 0.7422
Epoch 12/100
462/462 [==============================] - 1s 1ms/step - loss: 0.5062 - accuracy: 0.7533
Epoch 13/100
462/462 [==============================] - 0s 1ms/step - loss: 0.5116 - accuracy: 0.7465
Epoch 14/100
462/462 [==============================] - 0s 1ms/step - loss: 0.5109 - accuracy: 0.7443
Epoch 15/100
462/462 [==============================] - 0s 1ms/step - loss: 0.5132 - accuracy: 0.7454
Epoch 16/100
462/462 [==============================] - 0s 1ms/step - loss: 0.5100 - accuracy: 0.7466
Epoch 17/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4956 - accuracy: 0.7521
Epoch 18/100
462/462 [==============================] - 0s 1ms/step - loss: 0.5068 - accuracy: 0.7460
Epoch 19/100
462/462 [==============================] - 0s 1ms/step - loss: 0.5040 - accuracy: 0.7503
Epoch 20/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4913 - accuracy: 0.7559
Epoch 21/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4907 - accuracy: 0.7546
Epoch 22/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4953 - accuracy: 0.7541
Epoch 23/100
462/462 [==============================] - 1s 1ms/step - loss: 0.4901 - accuracy: 0.7594
Epoch 24/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4850 - accuracy: 0.7614
Epoch 25/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4872 - accuracy: 0.7585
Epoch 26/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4799 - accuracy: 0.7646
Epoch 27/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4716 - accuracy: 0.7696
Epoch 28/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4726 - accuracy: 0.7709
Epoch 29/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4748 - accuracy: 0.7685
Epoch 30/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4777 - accuracy: 0.7628
Epoch 31/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4671 - accuracy: 0.7739
Epoch 32/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4648 - accuracy: 0.7765
Epoch 33/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4709 - accuracy: 0.7732
Epoch 34/100
462/462 [==============================] - 1s 1ms/step - loss: 0.4608 - accuracy: 0.7729
Epoch 35/100
462/462 [==============================] - 1s 1ms/step - loss: 0.4625 - accuracy: 0.7784
Epoch 36/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4614 - accuracy: 0.7791
Epoch 37/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4583 - accuracy: 0.7783
Epoch 38/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4619 - accuracy: 0.7742
Epoch 39/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4599 - accuracy: 0.7735
Epoch 40/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4562 - accuracy: 0.7780
Epoch 41/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4552 - accuracy: 0.7798
Epoch 42/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4592 - accuracy: 0.7758
Epoch 43/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4604 - accuracy: 0.7757
Epoch 44/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4547 - accuracy: 0.7806
Epoch 45/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4585 - accuracy: 0.7776
Epoch 46/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4562 - accuracy: 0.7775
Epoch 47/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4627 - accuracy: 0.7731
Epoch 48/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4579 - accuracy: 0.7748
Epoch 49/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4547 - accuracy: 0.7775
Epoch 50/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4507 - accuracy: 0.7825
Epoch 51/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4471 - accuracy: 0.7820
Epoch 52/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4520 - accuracy: 0.7768
Epoch 53/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4491 - accuracy: 0.7825
Epoch 54/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4453 - accuracy: 0.7831
Epoch 55/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4422 - accuracy: 0.7848
Epoch 56/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4439 - accuracy: 0.7857
Epoch 57/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4443 - accuracy: 0.7841
Epoch 58/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4478 - accuracy: 0.7815
Epoch 59/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4464 - accuracy: 0.7857
Epoch 60/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4441 - accuracy: 0.7840
Epoch 61/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4393 - accuracy: 0.7923
Epoch 62/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4365 - accuracy: 0.7886
Epoch 63/100
462/462 [==============================] - 1s 1ms/step - loss: 0.4396 - accuracy: 0.7883
Epoch 64/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4395 - accuracy: 0.7925
Epoch 65/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4400 - accuracy: 0.7859
Epoch 66/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4413 - accuracy: 0.7881
Epoch 67/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4320 - accuracy: 0.7919
Epoch 68/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4305 - accuracy: 0.7954
Epoch 69/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4347 - accuracy: 0.7930
Epoch 70/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4409 - accuracy: 0.7850
Epoch 71/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4360 - accuracy: 0.7882
Epoch 72/100
462/462 [==============================] - 1s 1ms/step - loss: 0.4314 - accuracy: 0.7911
Epoch 73/100
462/462 [==============================] - 1s 1ms/step - loss: 0.4299 - accuracy: 0.7926
Epoch 74/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4328 - accuracy: 0.7922
Epoch 75/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4326 - accuracy: 0.7920
Epoch 76/100
462/462 [==============================] - 1s 1ms/step - loss: 0.4254 - accuracy: 0.7933
Epoch 77/100
462/462 [==============================] - 1s 1ms/step - loss: 0.4218 - accuracy: 0.7987
Epoch 78/100
462/462 [==============================] - 1s 1ms/step - loss: 0.4152 - accuracy: 0.8019
Epoch 79/100
462/462 [==============================] - 1s 1ms/step - loss: 0.4172 - accuracy: 0.8014
Epoch 80/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4166 - accuracy: 0.7998
Epoch 81/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4097 - accuracy: 0.8051
Epoch 82/100
462/462 [==============================] - 1s 1ms/step - loss: 0.4103 - accuracy: 0.8032
Epoch 83/100
462/462 [==============================] - 1s 1ms/step - loss: 0.4106 - accuracy: 0.8057
Epoch 84/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4120 - accuracy: 0.8055
Epoch 85/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4079 - accuracy: 0.8066
Epoch 86/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4129 - accuracy: 0.7999
Epoch 87/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4126 - accuracy: 0.8027
Epoch 88/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4075 - accuracy: 0.8024
Epoch 89/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4005 - accuracy: 0.8058
Epoch 90/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4031 - accuracy: 0.8094
Epoch 91/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4044 - accuracy: 0.8056
Epoch 92/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4030 - accuracy: 0.8084
Epoch 93/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4033 - accuracy: 0.8101
Epoch 94/100
462/462 [==============================] - 0s 1ms/step - loss: 0.3997 - accuracy: 0.8115
Epoch 95/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4054 - accuracy: 0.8071
Epoch 96/100
462/462 [==============================] - 0s 1ms/step - loss: 0.4018 - accuracy: 0.8051
Epoch 97/100
462/462 [==============================] - 1s 1ms/step - loss: 0.3941 - accuracy: 0.8142
Epoch 98/100
462/462 [==============================] - 0s 1ms/step - loss: 0.3927 - accuracy: 0.8145
Epoch 99/100
462/462 [==============================] - 0s 1ms/step - loss: 0.3973 - accuracy: 0.8105
Epoch 100/100
462/462 [==============================] - 0s 1ms/step - loss: 0.3894 - accuracy: 0.8094

In [31]:
model.evaluate(X_test,y_test)

116/116 [==============================] - 0s 853us/step - loss: 0.3909 - accuracy: 0.8195

[0.3908624053001404, 0.8195346593856812]

In [32]:
df2=pd.read_csv('test2.csv')

In [33]:
df2

,ID_Patient_Care_Situation,Diagnosed_Condition,Patient_ID,Treated_with_drugs,Patient_Age,Patient_Body_Mass_Index,Patient_Smoker,Patient_Rural_Urban,Patient_mental_condition,A,B,C,D,E,F,Z,Number_of_prev_cond
0,9913,2,10247,DX6,7,23.489639,NO,RURAL,Stable,1.0,0.0,1.0,1.0,1.0,0.0,0.0,4.0
1,20681,40,10919,DX6,66,21.941882,NO,URBAN,Stable,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0
2,2264,18,5283,DX3,3,24.579787,NO,URBAN,Stable,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,21587,40,7442,DX1 DX4,9,17.832771,NO,URBAN,Stable,1.0,0.0,1.0,1.0,0.0,0.0,0.0,3.0
4,15876,46,3845,DX1 DX3,64,28.829848,YES,RURAL,Stable,1.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4615,18001,26,5060,DX4,6,22.289060,NO,RURAL,Stable,1.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0
4616,24900,26,11169,DX4,65,25.419644,NO,RURAL,Stable,1.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0
4617,10998,38,658,DX6,2,18.102259,NO,URBAN,Stable,1.0,1.0,1.0,0.0,0.0,0.0,0.0,3.0
4618,25628,49,966,DX6,0,23.400026,NO,URBAN,Stable,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4619,18217,46,9047,DX1,0,24.416926,NO,RURAL,Stable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
df2.isnull().sum()

ID_Patient_Care_Situation      0
Diagnosed_Condition            0
Patient_Age                    0
Patient_Body_Mass_Index        0
A                            230
B                            230
C                            230
D                            230
E                            230
F                            230
Z                            230
Number_of_prev_cond          230
DX1                            0
DX2                            0
DX3                            0
DX4                            0
DX5                            0
DX6                            0
Cannot say                     0
NO                             0
YES                            0
RURAL                          0
URBAN                          0
dtype: int64

In [56]:
cols_nan=['A','B','C','D','E','F','Z']
for cols in cols_nan:
    df2[cols].fillna(0,inplace=True)

In [57]:
df2['Number_of_prev_cond'].fillna(df2['A']+df2['B']+df2['C']+df2['D']+df2['E']+df2['F']+df2['Z'],inplace=True)

In [58]:
df2.isnull().sum()

ID_Patient_Care_Situation    0
Diagnosed_Condition          0
Patient_Age                  0
Patient_Body_Mass_Index      0
A                            0
B                            0
C                            0
D                            0
E                            0
F                            0
Z                            0
Number_of_prev_cond          0
DX1                          0
DX2                          0
DX3                          0
DX4                          0
DX5                          0
DX6                          0
Cannot say                   0
NO                           0
YES                          0
RURAL                        0
URBAN                        0
dtype: int64

In [35]:
df2['Treated_with_drugs'].unique()

array(['DX6', 'DX3 ', 'DX1 DX4 ', 'DX1 DX3 ', 'DX2 DX4 DX5 ',
       'DX1 DX3 DX4 ', 'DX2 ', 'DX2 DX3 DX4 ', 'DX1 ', 'DX3 DX4 ', 'DX4 ',
       'DX5 ', 'DX3 DX5 ', 'DX1 DX4 DX5 ', 'DX2 DX4 ', 'DX1 DX5 ',
       'DX2 DX3 ', 'DX1 DX2 DX4 ', 'DX1 DX3 DX5 ', 'DX4 DX5 ', 'DX1 DX2 ',
       'DX2 DX5 ', 'DX1 DX2 DX5 ', 'DX1 DX2 DX4 DX5 ', 'DX1 DX2 DX3 ',
       'DX1 DX2 DX3 DX5 ', 'DX3 DX4 DX5 ', 'DX2 DX3 DX5 ',
       'DX1 DX2 DX3 DX4 ', nan, 'DX1 DX3 DX4 DX5 ', 'DX2 DX3 DX4 DX5 '],
      dtype=object)

In [36]:
df3=pd.DataFrame(np.zeros((4620,6)))
df3.columns=['DX1','DX2','DX3','DX4','DX5','DX6']
count_row=0
for row in df2['Treated_with_drugs']:   
    val=str(row).split(" ")
    for value in val:
        if value == 'DX1':
            df3.loc[count_row,"DX1"]=1
        elif value == 'DX2':
            df3.loc[count_row,"DX2"]=1
        elif value == 'DX3':
            df3.loc[count_row,"DX3"]=1
        elif value == 'DX4':
            df3.loc[count_row,"DX4"]=1
        elif value == 'DX5':
            df3.loc[count_row,"DX5"]=1
        elif value == 'DX6':
            df3.loc[count_row,"DX6"]=1
    count_row+=1
df3

      DX1  DX2  DX3  DX4  DX5  DX6
0     0.0  0.0  0.0  0.0  0.0  1.0
1     0.0  0.0  0.0  0.0  0.0  1.0
2     0.0  0.0  1.0  0.0  0.0  0.0
3     1.0  0.0  0.0  1.0  0.0  0.0
4     1.0  0.0  1.0  0.0  0.0  0.0
...   ...  ...  ...  ...  ...  ...
4615  0.0  0.0  0.0  1.0  0.0  0.0
4616  0.0  0.0  0.0  1.0  0.0  0.0
4617  0.0  0.0  0.0  0.0  0.0  1.0
4618  0.0  0.0  0.0  0.0  0.0  1.0
4619  1.0  0.0  0.0  0.0  0.0  0.0

[4620 rows x 6 columns]

In [38]:
df2=pd.concat([df2,df3],axis=1)

In [40]:
cols_del=['Patient_mental_condition','Patient_ID','Treated_with_drugs']
for cols in cols_del:
    df2.drop(cols,inplace=True,axis=1)

In [41]:
col_dum=['Patient_Smoker','Patient_Rural_Urban']
for cols in col_dum:
    dummies=pd.get_dummies(df2[cols])
    df2=pd.concat([df2,dummies],axis=1)
df2.drop(col_dum,axis=1,inplace=True)

In [42]:
cols_to_scale=['ID_Patient_Care_Situation','Diagnosed_Condition','Patient_Body_Mass_Index','Patient_Age']
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
df2[cols_to_scale]=scaler.fit_transform(df2[cols_to_scale])

In [44]:
df2.shape

(4620, 23)

In [59]:
predict=model.predict(df2)

In [60]:
result=[]
for val in predict:
    if val>0.5:
        result.append(1)
    else:
        result.append(0)

In [61]:
result

[1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 ...]

In [62]:
model.evaluate(df2,result)

ValueError: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, (<class 'list'> containing values of types {"<class 'int'>"})

In [72]:
df4=pd.read_csv('test2.csv')

In [73]:
final=pd.DataFrame(df4['ID_Patient_Care_Situation'])

In [74]:
final.reset_index(drop=True,inplace=True)

In [75]:
final

      ID_Patient_Care_Situation
0                          9913
1                         20681
2                          2264
3                         21587
4                         15876
...                         ...
4615                      18001
4616                      24900
4617                      10998
4618                      25628
4619                      18217

[4620 rows x 1 columns]

In [76]:
final['Survived_1_year']=result

In [77]:
final

      ID_Patient_Care_Situation  Survived_1_year
0                          9913                1
1                         20681                0
2                          2264                1
3                         21587                0
4                         15876                0
...                         ...              ...
4615                      18001                1
4616                      24900                1
4617                      10998                0
4618                      25628                1
4619                      18217                1

[4620 rows x 2 columns]

In [78]:
final.to_csv('submit.csv',encoding='utf-8',index=None)